### ISSUE TITLE
Feature request: Add CTLD

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPUF#2]
@132nd-Entropy Would it be possible to add CTLD to OPUF, and place zones at all airfield, FOB  and FARPs?
 All MI-8's and current road convoys should be added as logistical units that can load tropps.

**Comment by 132nd-Entropy** [comment]
wilco!

**Comment by 132nd-Entropy** [comment]
"259  FARP LONDON #1",
    "259  FARP LONDON #2",    
    "259  FARP LONDON #3",
    "259  FARP LONDON #4",
	"MI-8 Al Dahfra #1 - Park 87",
	"MI-8 Al Dahfra #1 - Park 88", 
	"MI-8 Al Dahfra #1 - Park 89", 
	"MI-8 Al Dahfra #1 - Park 90",
	"FOB_Blackfoot_Convoy1",  	

is the list of convoys and transport helos that I found, please add the group names if anything is missing

**Comment by 132nd-Entropy** [comment]
name of zones where infantry can be loaded up 

    { "Al Dhafra", "none", -1, "yes", 0 },
	{ "Al Minhad", "none", -1, "yes", 0 },
	{ "log MASAFI", "none", -1, "yes", 0 },
	{ "FOB Blackfoot", "none", -1, "yes", 0 },
	{ "Fujairah", "none", -1, "yes", 0 },
        { "FARP LONDON", "none", -1, "yes", 0 },

**Comment by 132nd-Entropy** [comment]
for crate-spawning 
{
    "Warehouse Al Minhad",
	"Warehouse Al Dhafra",
}
