### ISSUE TITLE
db_countries update

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/OPUF#4]
For mission design some flexibility helps. If this is added to the db_countries you get all the things for Iran. This would help
```
function merge_all_units_to_IRAN()
	local IRAN = country:get("IRAN")
	for i,o in pairs(country.by_country) do
		if o ~= IRAN then
			merge_unit_list_coutry(o,IRAN)
		end
	end
end
merge_all_units_to_IRAN()
```

**Comment by thebgpikester** [comment]
By the way tested, it works.

**Comment by thebgpikester** [comment]
It doesn't add chinese asset pack stuf and some other new things. I recommend using another line under Iran for

cnt_unit( units.Planes.Plane, "KJ-2000"); 

for the awacs chinese version so it can be use with an iranian skin for the skin pack

**Comment by thebgpikester** [comment]
OK completed the 132nd change on the countries to support all normal assets now are belonging to Iran and adding the KJ-2000 awacs to support the Iranian Skin.
[db_countries .txt](https://github.com/132nd-vWing/OPUF/files/2426264/db_countries.txt)

**Comment by thebgpikester** [comment]
[db_countries.txt](https://github.com/132nd-vWing/OPUF/files/2426325/db_countries.txt)
OK here are the proposed changes to db_countries.lua (text attached and tested)
IRAN now has all "regular" assets 
IRAN now has the Chinese ships 
IRAN has the Chinese AWACS --this fits the Iranian skin in the skin pack
The lua is otherwise still containing the previous 132nd changes. Submitted for consideration

**Comment by 132nd-Entropy** [comment]
thanks will test!!

**Comment by 132nd-Entropy** [comment]
lua didnt contain the previous 132nd changes but I added them back in, now its completed. Thanks a ton for the help!!
