### ISSUE TITLE
Iranian Mirage skin

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/OPUF#5]
I've tried. I really have. I didn't find anything. i'm useless with PS, im a gimp user and the dds plugin is broke for it. So i've given up. I would like an Iranian themed skin for OPUF, please.

**Comment by jkhoel** [comment]
I believe I still have the Mirage templates. Did you collect any reference material for this yet?

Would [something based of a more modern F-14 skin work?](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2F123279-352727-raikfcquaxqncofqfm.stackpathdns.com%2Fwp-content%2Fuploads%2F2016%2F08%2FHobby-Master-HA5205-%E2%80%93-F-14AM-Tomcat-Diecast-Model-Front-Starboard-View.jpg&f=1)

**Comment by 132ndNeck** [comment]
@jkhoel have created one, and @132nd-Entropy have added it to the OvGME repo.

Issue is closed.
