### ISSUE TITLE
A2Ground Dispatcher?

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/OPUF#6]
So, this may, or may not, be of use.

The concept is, that you can script CAS, and strike responses from the AI side, based on realtime information during the mission. The process goes like this:

1. Create script etc.
2. Have the Red forces in proximity to Blue Ground forces. This can be via Drone (best) or Troops in contact.
3. The red side will detect Blue Ground units and dispatch AI strikers to attack those targets.

Concept video to explain.
https://www.youtube.com/watch?v=qV6nYSKggUE

**Comment by 132ndNeck** [comment]
It is absolutely of interest. 
Is it resource demanding? (when running, for the server?)

**Comment by thebgpikester** [comment]
scripts in general are never resource demanding, But what is, is the amount of extra aircraft that is created (and the resulting combat) multiplied by player numbers.

We've tested insane amounts on the Red servers and you can cope but perhaps the factor is how many people join..

It's a lot safer for striker and enemy chopper AI to be let loose on a server than fighters. Makes CAP more about prevention.

Since this post I've created some very cool automated stuff for both sides that I'm now happy to give away to 132nd that pretty much makes red's fight back and clear out zones. I should demo this instead as it's all manual and not very moose at all.

**Comment by 132ndNeck** [comment]
Sounds great. Send me info on PM on discord for the demo and we can see how we fit it in.

**Comment by 132ndNeck** [comment]
Closed this. And we can use Issue #15 for the continued discussion for this
