### ISSUE TITLE
SAM units move when fired upon (HARM)

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPUF#7]
Is it possible to setup so that the specific unit (within the group) that is fired up by a HARM shuts down its radar, and moves to a randomly new location? This so not the entire group starts moving, but only the Radar that is actually beeing fired upon.

**Details:**
- Random delay of 4-8 seconds after launch of the HARM trigger the activity (To simulate they actually beeing able to detect the missile before moving)
- Shut down radar
- Move to a random location 50-150m away from its current location when shot at
- 15% chance that it will not  move at all (So SEAD not always work 100%, so SEAD pilots need to verify if SEAD is effective).
- IF POSSIBLE: Possible to use a simple label as part of the group name to get this to work (Increased flexibility in the ME, as people can just add a unit, and make sure to include the pre-fix or part that is needed for it to be recognized by the script.
- A 5% chance that the entire group shuts down, and the entire group move to a new location 1000m away (so it takes a lot more time, and it is out of action for some time)

**Comment by 132nd-Entropy** [comment]
everything above implemented, within the script, you will find your 'control panel', and values can be changed 

local evasion = true     -- set to false to disable evasive behavior for Radar units
local chance_for_evasive_action = 85 -- percent chance that the Radar unit will take evasive action
local prefix = "evade_"  -- all SAM that should be added to the script need to have these word within their GROUP NAME
local Target_Smoke = false           -- set to TRUE if you want red smoke deployed from the Target SAM  (mainly used for debugging)
local evasion_delay = math.random(4,8)  -- after HARM launch, delay in seconds until the SAM take evasive action
local radar_delay = math.random(120,300)   -- time in seconds until the unit will turn its radar back on (random number between the two)
local move_distance =  math.random(50,150)-- meters the unit will move before stopping (random number between the two)
local evasion_for_client_planes_only = true -- set to false if Sam Radars should also respond to AI planes firing
local chance_for_group_relocating = 5   --percent chance that the group shuts down and moves to a new location further away
local relocating_distance = math.random(800,1200)  -- distance in meters that the group relocates

**Comment by 132ndNeck** [comment]
This works great! Thanks
